# Generated by Django 3.2.3 on 2021-06-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9, verbose_name='Rut sin punto ni guión')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('Apellido_paterno', models.CharField(max_length=40, verbose_name='Apellido Paterno')),
                ('Apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('edad', models.IntegerField(verbose_name='Edad ')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=70, verbose_name='apellidos')),
                ('correo', models.CharField(max_length=90, verbose_name='correo')),
                ('contrasenia', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
        ),
        migrations.DeleteModel(
            name='camilo',
        ),
        migrations.DeleteModel(
            name='Edad',
        ),
    ]
